<?php

namespace ERP\DocumentBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

class DocumentController extends ParentController
{
    /**
     * @Route(
     *     "admin/erp/document/document",
     *     name="admin_erp_document_document_table"
     * )
     */
    public function tableAction($parameters = null)
    {
        $parameters['repository_method'] = "findBySheet";
        $parameters['repository_argument'] = $this->getActiveSheet();
        return parent::tableAction($parameters); // TODO: Change the autogenerated stub
    }

    /**
     * @Route(
     *     "admin/erp/document/document/add",
     *     name="admin_erp_document_document_add"
     * )
     */
    public function addAction(Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = "referer";
        $parameters['formAction'] = $this->generateUrl('admin_erp_document_document_add');

        return parent::addAction($request, $parameters);
    }

    /**
     * @Route(
     *     "admin/erp/document/document/update/{id}",
     *     name="admin_erp_document_document_update",
     *     requirements={"id" = "\d+"}
     * )
     */
    public function updateAction($id, Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = "referer";
        $parameters['formAction'] = $this->generateUrl('admin_erp_document_document_update', [
            "id" => $id
        ]);

        return parent::updateAction($id, $request, $parameters);
    }

    /**
     * @Route(
     *     "admin/erp/document/document/delete/{id}",
     *     name="admin_erp_document_document_delete",
     *     requirements={"id" = "\d+"},
     *     options = {"expose" = true}
     * )
     */
    public function deleteAction($id, Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = $this->generateUrl('admin_erp_document_document_table');

        return parent::deleteAction($id, $request, $parameters);
    }
}
