<?php

namespace ERP\DocumentBundle\Controller;

use ERP\DocumentBundle\Entity\Sheet;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Request;

class SheetController extends ParentController
{
    /**
     * @Route(
     *     "admin/erp/document/sheet/switch/{id}",
     *     name="admin_erp_document_sheet_switch",
     *     requirements={"id" = "\d+"}
     * )
     */
    public function switchAction(Sheet $id, Request $request)
    {
        $this->setActiveSheet($id);

        if($request->query->get('redirection'))
            return $this->redirectToRoute($request->query->get('redirection'));
        return $this->redirect($this->getPreviousRoute($request) ?? $this->generateUrl('admin_erp_document_document_table'));
    }

    /**
     * @Route(
     *     "admin/erp/document/sheet/table",
     *     name="admin_erp_document_sheet_table"
     * )
     */
    public function tableAction($parameters = null)
    {
        $parameters['repository_method'] = "findByUser";
        $parameters['repository_argument'] = $this->getUser();
        return parent::tableAction($parameters); // TODO: Change the autogenerated stub
    }

    /**
     * @Route(
     *     "admin/erp/document/sheet/add",
     *     name="admin_erp_document_sheet_add"
     * )
     */
    public function addAction(Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = "referer";
        $parameters['formAction'] = $this->generateUrl('admin_erp_document_sheet_add');

        return parent::addAction($request, $parameters);
    }

    /**
     * @Route(
     *     "admin/erp/document/sheet/update/{id}",
     *     name="admin_erp_document_sheet_update",
     *     requirements={"id" = "\d+"}
     * )
     */
    public function updateAction($id, Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = "referer";
        $parameters['formAction'] = $this->generateUrl('admin_erp_document_sheet_update', [
            "id" => $id
        ]);

        return parent::updateAction($id, $request, $parameters);
    }

    /**
     * @Route(
     *     "admin/erp/document/sheet/delete/{id}",
     *     name="admin_erp_document_sheet_delete",
     *     requirements={"id" = "\d+"},
     *     options = {"expose" = true}
     * )
     */
    public function deleteAction($id, Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = $this->generateUrl('admin_erp_document_sheet_table');

        return parent::deleteAction($id, $request, $parameters);
    }
}
