<?php

namespace ERP\ProductBundle\Controller;

use ERP\DocumentBundle\Entity\Sheet;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Request;

class ProductController extends ParentController
{
    /**
     * @Route(
     *     "admin/erp/product/product/table",
     *     name="admin_erp_product_product_table"
     * )
     */
    public function tableAction($parameters = null)
    {
        $parameters['repository_method'] = "findByUser";
        $parameters['repository_argument'] = $this->getUser();
        return parent::tableAction($parameters);
    }

    /**
     * @Route(
     *     "admin/erp/product/product/add",
     *     name="admin_erp_product_product_add"
     * )
     */
    public function addAction(Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = "referer";
        $parameters['formAction'] = $this->generateUrl('admin_erp_product_product_add');

        return parent::addAction($request, $parameters); // TODO: Change the autogenerated stub
    }

    /**
     * @Route(
     *     "admin/erp/product/product/update/{id}",
     *     name="admin_erp_product_product_update",
     *     requirements={"id" = "\d+"}
     * )
     */
    public function updateAction($id, Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = "referer";
        $parameters['formAction'] = $this->generateUrl('admin_erp_product_product_update', [
            "id" => $id
        ]);

        return parent::updateAction($id, $request, $parameters);
    }

    /**
     * @Route(
     *     "admin/erp/product/product/delete/{id}",
     *     name="admin_erp_product_product_delete",
     *     requirements={"id" = "\d+"},
     *     options = {"expose" = true}
     * )
     */
    public function deleteAction($id, Request $request, $parameters = null)
    {
        $parameters['redirectTo'] = $this->generateUrl('admin_erp_product_product_delete');

        return parent::deleteAction($id, $request, $parameters);
    }
}
