<?php

namespace ERP\ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($user)
    {
        $bq = $this->createQueryBuilder("p")
            ->where("p.user = :user")
            ->orderBy('p.code', 'ASC')
            ->setParameters([
                "user" => $user
            ]);
        return $bq->getQuery()->getResult();
    }
}
